### ISSUE TITLE
Rendered string results do not honor New Lines. (\r\n, Environment.NewLine, etc)

### ISSUE THREAD

**Issue by pianomanjh** [Microsoft/workbooks#117]
#### Xamarin Workbooks
| Detail          | Value                       |
| :-------------- | :-------------------------- |
| Version         | 1.4.0-beta1                 |
| Git Branch      | master                      |
| Git Hash        | 2e30f47                     |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component       | Value                                      |
| :-------------- | :----------------------------------------- |
| Windows         | Microsoft Windows NT 10.0.16299.0 (64-bit) |
| CPU Cores       | 8                                          |
| Physical Memory | 16 GB                                      |

#### System-Installed Software
| Component       | Version  |
| :-------------- | :------- |
| Xamarin iOS     | 10.4.0   |
| Xamarin Android | 7.1.0-19 |

#### VisualStudio.15.Release Components
| Component                       | Version           |
| :------------------------------ | :---------------- |
| Visual Studio Professional 2017 | 15.4.5+27004.2010 |
| Xamarin iOS                     | 11.3.0-47         |
| Xamarin Android                 | 8.0.2-1           |

### Steps to Reproduce

1. Create a code block of just `string foo = "test\ntest";` and execute

### Expected Behavior
Rendered result is
"test
test"

### Actual Behavior
Rendered result is 
"test\ntest"

Ideally, we would get the control characters honored, as it would appear in any other text editor.

**Comment by sandyarmstrong** [comment]
You just need to switch from the "C#" renderer to the "Plain Text" renderer.

![image](https://user-images.githubusercontent.com/155076/33559553-064c9138-d8c2-11e7-806f-9d6ebee743e2.png)
