### ISSUE TITLE
Error initializing Android tools

### ISSUE THREAD

**Issue by KristofferBerge** [Microsoft/workbooks#118]
### Environment
Windows 10
Android SDK installed via Visual studio 2017 v15.4.5
Tested with both version 1.3.2 and 1.4.0 Beta-1

**Log File**
[Xamarin Workbooks 2017-12-04.log](https://github.com/Microsoft/workbooks/files/1527752/Xamarin.Workbooks.2017-12-04.log)

#### Xamarin Workbooks
| Detail          | Value                       |
| :-------------- | :-------------------------- |
| Version         | 1.4.0-beta1                 |
| Git Branch      | master                      |
| Git Hash        | 2e30f47                     |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component       | Value                                      |
| :-------------- | :----------------------------------------- |
| Windows         | Microsoft Windows NT 10.0.15063.0 (64-bit) |
| CPU Cores       | 4                                          |
| Physical Memory | 16 GB                                      |

#### VisualStudio.15.Release Components
| Component                       | Version           |
| :------------------------------ | :---------------- |
| Visual Studio Professional 2017 | 15.4.5+27004.2010 |
| Xamarin iOS                     | 11.3.0-47         |
| Xamarin Android                 | 8.0.2-1           |

### Steps to Reproduce

1. Open any workbook using the Android SDK

**Comment by sandyarmstrong** [comment]
Relevant discussion: https://gitter.im/Microsoft/workbooks?at=5a25677f3a80a84b5bb66d43

**Comment by sandyarmstrong** [comment]
@KristofferBerge you mentioned in gitter that `C:\Program Files (x86)\Android\android-sdk` exists. What about `C:\Program Files (x86)\Android\android-sdk\platform-tools`?

Locally I have run into what appears to be a VS installer bug where my android sdk install got mangled, and I'm wondering if you have the same problem.

**Comment by KristofferBerge** [comment]
Yes, the platform-tools folder is there.

I installed Visual Studio 2017 with the Xamarin option selected under workloads:
![xamarin workload](https://user-images.githubusercontent.com/1595367/33821188-31079a30-de53-11e7-97b9-bc368f7dc7b0.PNG)

![xamarin](https://user-images.githubusercontent.com/1595367/33821075-c41f08b8-de52-11e7-81cf-c2c060e10981.PNG)

Debugging android applications in an emulator in Visual Studio works fine

**Comment by sandyarmstrong** [comment]
If you go to `Tools > Options > Xamarin > Android Settings`, what path do you see in `Android SDK Location`?

![image](https://user-images.githubusercontent.com/155076/33836869-863ee3aa-de3f-11e7-93f6-810c6a77b763.png)

**Comment by KristofferBerge** [comment]
Android SDK location is exactly the same as in your picture.

**Comment by sandyarmstrong** [comment]
I believe this is fixed now. Will close when we have a build out.

**Comment by sandyarmstrong** [comment]
Should be fixed in 1.4 RC1: https://dl.xamarin.com/interactive/XamarinInteractive-1.4.0-rc1.msi.
