### ISSUE TITLE
Mac: "False"/"True" next to checkboxes for bool properties should go away

### ISSUE THREAD

**Issue by sandyarmstrong** [Microsoft/workbooks#156]
It's unnecessary and kind of confusing, too.

![image](https://user-images.githubusercontent.com/155076/34311797-a76e2df0-e714-11e7-89e7-f4dda72b47c3.png)

**Comment by abock** [comment]
You need to move this to [proppy](https://github.com/xamarin/Xamarin.PropertyEditing). UI/UX things should be discussed there.
