### ISSUE TITLE
Inspector add in breaks Xamarin.Forms on iOS

### ISSUE THREAD

**Issue by rmarinho** [Microsoft/workbooks#165]
### Steps to Reproduce

1. Clone [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms) repo
2. Run the iOS gallery with Inspector add in enable

### Expected Behavior

Should work just fine and launch the gallery 

### Actual Behavior

it will fail when registering the renderers

`System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies`

### Environment

Stable xamarin

**Comment by sandyarmstrong** [comment]
@hartez experienced this on Windows with VS 15.5 and Workbooks 1.3.2, where `Xamarin.Interactive` is still a PCL. Perhaps this is a problem when using newer XF with those older agent files?

**Comment by sandyarmstrong** [comment]
Should be fixed in 1.4.1 and later, available in VS 15.8 P4.
