### ISSUE TITLE
Make it possible to build the Windows installer without iOS or Android support

### ISSUE THREAD

**Issue by abock** [Microsoft/workbooks#176]
* iOS support requires XVS set up to build iOS on a Mac build host
* Android support is proprietary, but our Windows installer unconditionally refers to bits the proprietary component build produces

This makes testing a complete build from the open-source tree a bit tedious.

**Comment by sandyarmstrong** [comment]
Realistically I think this should block on https://github.com/Microsoft/workbooks/issues/22. It will be a lot easier to do in a world where we have already split out workbook app builds, and also when we have removed the agent files that are there to support older Inspector extensions (before 15.6).

**Comment by abock** [comment]
That's probably ideal, but I also was able to make a minimum amount of changes that allowed me to build an installer. It's easy to deal with today from the `.wxiproj`. What I'm not sure about is if you can conditionally select nodes in the `.wxs`.

I'll post my patch here and maybe you'll have some ideas.

**Comment by bojanrajkovic** [comment]
I don't believe you can, but we can conditionally include .wxs'es in the project.

**Comment by abock** [comment]
The issue is the `<ComponentGroupRef>` nodes in `Product.wxs`. Here's the patch that resulted in an installer without Android or iOS support. I feel like there should be a simple way to do this now, and then we continue to clean up the installer layout after/as-part-of #22.

```diff
diff --git a/Package/Windows/Product.wxs b/Package/Windows/Product.wxs
index 43e22e6..a9ae0d4 100644
--- a/Package/Windows/Product.wxs
+++ b/Package/Windows/Product.wxs
@@ -54,10 +54,6 @@
       <ComponentGroupRef Id="ClientReplMonacoEditorVsEditorResources" />
       <ComponentGroupRef Id="DotNetCoreAgentAppComponents"/>
       <ComponentGroupRef Id="DotNetCoreAgentComponents"/>
-      <ComponentGroupRef Id="iOSWorkbookAppComponents"/>
-      <ComponentGroupRef Id="iOSWorkbookAppStoryboardComponents"/>
-      <ComponentGroupRef Id="iOSWorkbookAppFacadesComponents"/>
-      <ComponentGroupRef Id="iOSWorkbookAppClientIntegrationComponents"/>
       <ComponentGroupRef Id="WorkbookManifestComponents"/>

       <ComponentGroupRef Id="ClientSampleWorkbooks" />
diff --git a/Package/Windows/Xamarin.Interactive.Windows.Installer.wixproj b/Package/Windows/Xamarin.Interactive.Windows.Installer.wixproj
index 6f97ae7..a0311a7 100644
--- a/Package/Windows/Xamarin.Interactive.Windows.Installer.wixproj
+++ b/Package/Windows/Xamarin.Interactive.Windows.Installer.wixproj
@@ -37,7 +37,7 @@
     <Compile Include="TargetDir.wxs" />
     <Compile Include="RootFiles.wxs" />
     <Compile Include="ToolsFiles.wxs" />
-    <Compile Include="iOSWorkbookAppFiles.wxs" />
+    <Compile Include="iOSWorkbookAppFiles.wxs" Condition="Exists('..\..\_build\$(Configuration)\WorkbookApps\iOS\Xamarin.Workbooks.iOS.app')" />
     <Compile Include="AndroidAgentAppAssemblies.wxs" />
     <Compile Include="DotNetCoreAgentAppFiles.wxs" />
   </ItemGroup>
```

**Comment by abock** [comment]
Actually, that clearly has nothing to do with Android. I think I at that point I gave up and cloned `workbooks-proprietary`. Should be a similar issue though.
