### ISSUE TITLE
I do not  understand why I cannot change any color of text or background using the xamarin inspector

### ISSUE THREAD

**Issue by TianyiChen-1** [Microsoft/workbooks#192]
### Steps to Reproduce

1. 
2. 
3. 

#### Xamarin Inspector
| Detail | Value |
| :- | :- |
| Version | 1.4.0 |
| Git Branch | master |
| Git Hash | b3f92f9 |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component | Value |
| :- | :- |
| Windows | Microsoft Windows NT 10.0.16299.0 (64-bit) |
| CPU Cores | 4 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Xamarin Simulator | 1010202032 |

#### VisualStudio.15.Release Components
| Component | Version |
| :- | :- |
| Visual Studio Enterprise 2017 | 15.5.6+27130.2027 |
| Xamarin iOS | 11.6.1-4 |
| Xamarin Android | 8.1.5-0 |

**Comment by sandyarmstrong** [comment]
Hello! Can you give more information about what it is you're trying to do? What platform (iOS, Android, etc) is your app? What type of control are you trying to modify? How are you trying to make your change?
