### ISSUE TITLE
Unable to use Workbooks with Rx.Net 4.0.0-preview

### ISSUE THREAD

**Issue by giusepe** [Microsoft/workbooks#209]
### Steps to Reproduce

1. New project
2. Install nugets: System.Reactive and System.Reactive.Linq 4.0.0-preview
3. Try to run this: 
[BrokenCase.workbook.zip](https://github.com/Microsoft/workbooks/files/1786592/BrokenCase.workbook.zip)

### Expected Behavior
An output like:
False
True
False

### Actual Behavior
An error: `(12,16): error CS1061: 'Status[]' does not contain a definition for 'ToObservable' and no extension method 'ToObservable' accepting a first argument of type 'Status[]' could be found (are you missing a using directive or an assembly reference?)
`
Same steps work on a Console Application.

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.4.0 |
| Git Branch | master |
| Git Hash | b3f92f9 |
| VSTS Definition | Workbooks & Inspector (Mac) |

#### System Info
| Component | Value |
| :- | :- |
| macOS | Version 10.13.3 (Build 17D102) (64-bit) |
| CPU Cores | 8 / 8 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Mono | 5.4.1.7 |
| Xamarin Mac | 4.0.0.216 |
| Xamarin iOS | 11.6.1.4 |
| Xamarin Android | 8.1.5-0 |
| Visual Studio | 7.3.3.23 (703030023) |

### Log File

[Xamarin Workbooks 2018-03-06.log](https://github.com/Microsoft/workbooks/files/1786596/Xamarin.Workbooks.2018-03-06.log)

**Comment by sandyarmstrong** [comment]
You are missing `using System.Reactive.Linq;`.

**Comment by giusepe** [comment]
Oh... So the `#r "System.Reactive.Linq"` doesn't work as a `using` but really only as a reference?

**Comment by sandyarmstrong** [comment]
Correct. `#r` just gets the _assembly_ referenced. It does not inject any `using` statements automatically.

**Comment by giusepe** [comment]
Got it.

Thank you very much for your time and help. Appreciate it! :)
