### ISSUE TITLE
Xamarin.Forms + android samples are missing

### ISSUE THREAD

**Issue by atsushieno** [Microsoft/workbooks#250]
On the documentation page https://developer.xamarin.com/workbooks/ , there is no Xamarin.Forms samples for Android. In particular, there is a "ListView for Android" link, but the linked content is for iOS.

**Comment by sandyarmstrong** [comment]
Thanks, this is already filed (and a fix proposed if you want to play with it) at https://github.com/xamarin/Workbooks/issues/25.
