### ISSUE TITLE
The Loss of focus is observed on Add Package popup while navigating from "Show Pre-Release Packages" check box to "Cancel" button.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/workbooks#255]
### Steps to Reproduce

1.Launch Xamarin Workbook application and select platform(Mac (Mordern)) and create a new workbook.
2. Navigate to File->Add NuGet Package... and Hit on Enter to invoke it.
Scenario1: 
3. Without typing any of the elements in the "Search Nuget" edit box, traverse the "Show Pre-Release Packages" check box to "Cancel" button using Tab key. 

Scenario2:
3. Type any of the elements in the "Search Nuget" edit box-> list of the resulting package are thrown in the package window-> traverse the "Show Pre-Release Packages" check box to "Cancel" button using tab key. 

### Expected Behavior
Scenario1:
The user has not typed any of the package in the "Search Nuget" edit box, so no list of the packages are observed, so keyboard focus should jump from check-box to cancel button without any focus loss.

Scenario2:
Once the user has  typed any of the package in the "Search Nuget" edit box, and list of the packages are observed, so keyboard focus should jump from check-box to the outer boundary of the available lists to cancel button using tab key.

### Actual Behavior
Scenario1
Loss of focus is observed in the  Add Package popup while navigating from "Show Pre-Release Packages" to "Cancel" button without packages list.

Scenario 2:
Loss of focus is observed in Add Package popup while navigating from "Show Pre-Release Packages" to "Cancel" button with packages list using Tab key.
Note: Once user hit on tab key to move from check box to list of the available packages in a result, then focus loss is appeared. And at the time of the focus loss if user hits on Arrow key, keyboard focus is observed on the first list items of the resultant lists.

### User Impact:
The user might face difficulty to interact with the resulting available package lists.

### Environment
MAC: 10.13.4
Workbook - 1.4 (master/b3f92f9)
-->

**Comment by AccessibilityTestingTeam-TCS** [comment]
Exemption Approved - 1818
