### ISSUE TITLE
Loss of focus is observed upon pressing tab from "Show Workbook/Inspector view" buttons.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/workbooks#256]
### Steps to Reproduce

1.Launch Xamarin Workbook application and select platform and create a new workbook.
2. Navigate to Show Workbook/Inspector view button and press tab. Observe the keyboard focus. 

### Expected Behavior
Focus should move to next interactive element, which is in the Left pane of the workbooks.

### Actual Behavior
Focus loss is observed by hitting upon tab keys.

### User Impact
The User might be confuse with loss of keyboard focus.

### Environment
MAC: 10.13.4
Workbook - 1.4 (master/b3f92f9)-->

### Log File
![kb8_mainpane_inspectorbutton_focusloss](https://user-images.githubusercontent.com/22956130/39687904-f06af824-51bf-11e8-9328-c0378e44e229.png)

**Comment by WiproPSAccTest** [comment]
Please add the following labels to this bug:
A11yMAS
Accessibility
MAS2.4.3
Xamarin-Workbook-MAC
Wipro

**Comment by AccessibilityTestingTeam-TCS** [comment]
Exemption Approved - 1817
