### ISSUE TITLE
Keyboard focus is going to Non-Interactive element i.e.'Seperator'

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/workbooks#375]
### Steps to Reproduce
1. Launch Xamarin Workbooks application.This will invokes "Create a new Workbook" window.
2. Create a Workbook with WPF Platform.
4. Navigate to working platform combo-box (Beside Help Menu Tab) and change the platforms to different platforms (Console (.NET Framework)/ Console (.NET Core)/ Ios/ Android/ WPF).
### Expected Behavior
Keyboard focus should not go to Non-Interactive element 
### Actual Behavior
 Keyboard focus is going to Non-Interactive element i.e .'Separator'. 

Inspect Behavior:
Please refer below screenshot.
![screenshot 179](https://user-images.githubusercontent.com/22956130/40764832-0363ebb4-64c8-11e8-8f1c-6f802d24c8dd.png)

Narrator Behavior:
Please refer below screenshot.
![screenshot 180](https://user-images.githubusercontent.com/22956130/40764846-0d3b97f4-64c8-11e8-9237-79273c129937.png)

NVDA Behavior:
Please refer below screenshot.
![screenshot 181](https://user-images.githubusercontent.com/22956130/40764859-15ae0ce6-64c8-11e8-8642-4f59f8def0e9.png)

### User Impact:
User who rely on keyboard will try to access Non-Interactive separator element

### Screenshot:
![screenshot 185](https://user-images.githubusercontent.com/22956130/40764921-435afde8-64c8-11e8-85a4-0e4b90d6d64e.png)

### Environment
Windows : Version 1803 (OS Build : 17134.81)
Xamarin Version : 1.4(master/b3f92f9)

### Log File

**Comment by WiproPSAccTest** [comment]
Please add the following labels to the bug:
A11yMAS
Accessibility
Xamarin-Workbooks-Windows
Wipro
MAS2.4.3

**Comment by AccessibilityTestingTeam-TCS** [comment]
Exemption Approved - 1813
