### ISSUE TITLE
No active keyboard focus is present on the left pane tree elements in inspector view.

### ISSUE THREAD

**Issue by WiproPSAccTest** [Microsoft/workbooks#388]
### Steps to Reproduce
1. Launch Xamarin Workbooks application.This will invokes "Create a new Workbook" window.
2. Create a Workbook with WPF flatform.
3. Run a sample workbook code.
4. Invoke "Veiw Inspector" tab and navigate to tree present on left pane.

### Expected Behavior
Active keyboard focus should present on the left pane tree elements of Inspector.
### Actual Behavior
No active keyboard focus is present on the left pane tree elements of Inspector window.

Inspect Behavior:
Through the inspect, focus can be seen on left pane tree element "Hello Workbooks". Please refer below screenshot.
![screenshot 187](https://user-images.githubusercontent.com/22956130/40765599-908267f8-64ca-11e8-8bb0-63457321f317.png)
### User Impact:
User will not know whether the left tree elements got the focus or not.
### Screenshots:
![screenshot 188](https://user-images.githubusercontent.com/22956130/40765619-a9bca38c-64ca-11e8-8bf3-aa4096fb99c9.png)

### Environment
Windows : Version 1803 (OS Build : 17134.81)
Xamarin Version : 1.4(master/b3f92f9)
### Log File

**Comment by WiproPSAccTest** [comment]
Please add the following labels to the bug:
A11yMAS
Accessibility
Xamarin-Workbooks-Windows
Wipro
MAS2.4.7

**Comment by AccessibilityTestingTeam-TCS** [comment]
Exemption Approved - 1813
