### ISSUE TITLE
Phantom "Xamarin Workbooks" process eating CPU even after killing the app

### ISSUE THREAD

**Issue by ikomobi-apadol** [Microsoft/workbooks#407]
### Steps to Reproduce

1. On fresh mac start, launch Xamarin.Workbooks in Console targeting .NET Core
2. Create a workbook
3. The workbook gets stuck in "Connecting to agent" indefinitely
4. Open Mac Activity Monitor, order by CPU usage
5. Observe a Xamarin.Workbook process, taking up to 60 or 70% of CPU
6. Even if you kill the Xamarin.Workbook app, this background process keeps using the CPU

<img width="666" alt="screen shot 2018-06-11 at 12 15 46" src="https://user-images.githubusercontent.com/37339154/41226261-3ef5c6aa-6d71-11e8-88b1-1ccce164fe1a.png">

### Expected Behavior
When we leave Xamarin.Workbooks, it should kill any background process

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.4.0 |
| Git Branch | master |
| Git Hash | b3f92f9 |
| VSTS Definition | Workbooks & Inspector (Mac) |

#### System Info
| Component | Value |
| :- | :- |
| macOS | Version 10.13.4 (Build 17E202) (64-bit) |
| CPU Cores | 8 / 8 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Mono | 5.10.1.57 |
| Xamarin Mac | 4.4.1.193 |
| Xamarin iOS | 11.12.0.4 |
| Xamarin Android | 8.3.3-2 |
| Visual Studio | 7.5.2.40 (705020040) |

### Log File

[Xamarin Workbooks 2018-06-11.log](https://github.com/Microsoft/workbooks/files/2089540/Xamarin.Workbooks.2018-06-11.log)

**Comment by sandyarmstrong** [comment]
> The workbook gets stuck in "Connecting to agent" indefinitely

Does this happen to you every time you launch a .NET Core workbook?

**Comment by ikomobi-apadol** [comment]
Yes it does. I'm not the only one having this behavior in my team, at least 3 of us do (3 out of 6).
I don't thing I ever had this issue selecting the mono target

**Comment by fabiogaragiola** [comment]
I'm having the same issue if the `Xamarin Workbooks` background process is visible in the Activity Monitor.

![image](https://user-images.githubusercontent.com/6490745/41295379-c244083e-6e5a-11e8-9e78-3b44666cb78c.png)

If `Xamarin Workbooks` doesn't appear in the Activity Monitor, everything seems to work just fine  when using both .NET Core or the Mono runtime.

![image](https://user-images.githubusercontent.com/6490745/41294772-2759c012-6e59-11e8-8e64-369e81fd4050.png)

@sandyarmstrong just out of curiosity, what is this `Xamarin Workbooks` process all about? I initially thought it was the Mono runtime agent but the application seems to work properly when it's not running.

## Environment
### Xamarin Workbooks

Detail | Value
-- | --
Version | 1.4.0
Git Branch | master
Git Hash | b3f92f9

### System Info

Component | Value
-- | --
macOS | Version 10.13.5 (17F77) (64-bit)

### System-Installed Software

Component | Version
-- | --
Visual Studio | 7.6 Preview (7.6 build 947)
Mono | 5.12.0.260
.NET Core | 2.1.0
&nbsp; | 2.0.5
&nbsp; | 1.1.2
&nbsp; | 1.0.5


[Xamarin Workbooks 2018-06-12.log](https://github.com/Microsoft/workbooks/files/2094751/Xamarin.Workbooks.2018-06-12.log)

**Comment by sandyarmstrong** [comment]
@fabiogaragiola the Mono agent process actually just shows up in Activity Monitor as "mono-sgen64", because we don't bother to rename the process (we should start doing that, though).

The "Xamarin Workbooks" process that doesn't have the Workbooks icon next to it is (I think) a leftover process from a previous run of the Xamarin Workbooks app. We have seen this before, but usually only when we are debugging during development. I think it may be a Xamarin.Mac bug but we don't have enough information to say for sure right now. I am unable to reproduce the issue today.

Next time you see this, can you check what the Parent Process is for the Xamarin Workbooks process that is taking up all the CPU (you can do this by selecting the process in Activity Monitor and pressing <kbd>command</kbd><kbd>i</kbd>)? I am curious if it is "launchd" or if it actually points back to the PID for the current Xamarin Workbooks app instance.

**Comment by sandyarmstrong** [comment]
@fabiogaragiola @ikomobi-apadol honestly, the best way to diagnose would be if you could gist the full output of `ps -afx` next time you see this issue.

**Comment by fabiogaragiola** [comment]
@sandyarmstrong the "phantom" process points back to the PID for the current Xamarin Workbooks app instance:

![screen shot 2018-06-12 at 18 52 33](https://user-images.githubusercontent.com/6490745/41306094-4fa7a798-6e75-11e8-935c-07be12ed1912.png)

Here is the gist of `ps -afx` just after restarting the Mac and running into the issue again:

https://gist.github.com/fabiogaragiola/e1ead83219760044fae9bfd1db6da453

**Comment by sandyarmstrong** [comment]
@fabiogaragiola thanks, that is very strange but hopefully will help us figure this out!

**Comment by ikomobi-apadol** [comment]
@sandyarmstrong I downloaded the Xamarin.Workbooks update this morning, and since I have not been able to reproduce the bug I described above.
You guys did something for that release ? Or is it pure luck ?

**Comment by sandyarmstrong** [comment]
@ikomobi-apadol I do not think any of the changes in 1.4.1 would have fixed this problem.

I can still reproduce it when debugging, and it really does seem like the same issue. I think we'll leave this open.

@fabiogaragiola can you still reproduce this with 1.4.1?

**Comment by fabiogaragiola** [comment]
@sandyarmstrong nope, I cannot reproduce it anymore. The 1.4.1 works fine with my old workbooks that kept getting stuck last week. New workbooks seems to work fine as well. I didn't make extensive tests though.

**Comment by sandyarmstrong** [comment]
Very interesting. The only thing that could possibly be related (I think) is that we built the Mac client with a newer version of Xamarin.Mac in 1.4.1. Maybe something did change.

I'll close. Please feel free to reopen if you run into the problem again.
