### ISSUE TITLE
The "selectedView" is not working in the REPL

### ISSUE THREAD

**Issue by Krumelur** [Microsoft/workbooks#456]
### Steps to Reproduce

On the Mac:

1. Start an iOS app
2. Start inspector via VS' crosshair icon
3. Switch to the UI tree view
4. Select a view
5. Switch back to REPL
6. Type `selectedView`

### Expected Behavior
Info about the selected view should be shown.

### Actual Behavior
Error: `The name 'selectedView' does not exist in the current context`

### Environment
macOS

#### Xamarin Inspector
| Detail | Value |
| :- | :- |
| Version | 1.4.0 |
| Git Branch | master |
| Git Hash | b3f92f9 |
| VSTS Definition | Workbooks & Inspector (Mac) |

#### System Info
| Component | Value |
| :- | :- |
| macOS | Version 10.13.5 (Build 17F77) (64-bit) |
| CPU Cores | 8 / 8 |
| Physical Memory | 24 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Mono | 5.10.1.57 |
| Xamarin Mac | 4.4.1.193 |
| Xamarin iOS | 11.12.0.4 |
| Xamarin Android | 8.3.3-2 |
| Visual Studio | 7.5.2.40 (705020040) |
### Log File

[Xamarin Inspector 2018-06-25.log](https://github.com/Microsoft/workbooks/files/2133360/Xamarin.Inspector.2018-06-25.log)

**Comment by bojanrajkovic** [comment]
I wonder if this didn't regress when we plugged the new property editor in.

**Comment by sandyarmstrong** [comment]
I have a vague recollection that this is working in Windows but broken in Mac.

**Comment by bojanrajkovic** [comment]
Could be, I only tested on Mac this morning.

**Comment by sandyarmstrong** [comment]
This definitely works for WPF inspection on Windows. I believe it works for iOS inspection on Windows as well, but cannot test that just yet. So I believe this is a Mac client regression.

**Comment by sandyarmstrong** [comment]
Confirmed it works fine with iOS/Windows.

**Comment by sandyarmstrong** [comment]
This is fixed in the 1.4.2 Inspector client, which will be bundled in the next preview release of Visual Studio for Mac 7.6.
