### ISSUE TITLE
[Request ] Please add a method to halt the execution of a cell

### ISSUE THREAD

**Issue by instantiator** [Microsoft/workbooks#492]
### Steps to Reproduce

1. Create a cell with long-running code (eg. a number of HttpClient fetches, etc.)
2. Try to find a way to stop it! ;) 

NB. Either the way to stop execution is non-obvious, or (as I suspect) there isn't yet a way to do it. It would be extremely handy! Thanks!

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.4.3 |
| Git Branch | 1.4-release |
| Git Hash | db27525 |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component | Value |
| :- | :- |
| Windows | Microsoft Windows NT 10.0.17134.0 (64-bit) |
| CPU Cores | 4 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Xamarin iOS | 10.10.0 |
| Xamarin Android | 7.3.0-13 |

**Comment by sandyarmstrong** [comment]
You can hover over the "running" indicator, and reveal an "abort" button.

![image](https://user-images.githubusercontent.com/155076/45001031-882a1700-af7e-11e8-8e8f-c85855c34e41.png)

![image](https://user-images.githubusercontent.com/155076/45001035-911ae880-af7e-11e8-94ab-5c28906aede3.png)

Hope this helps; feel free to re-open if this still doesn't work for you.

**Comment by phillijw** [comment]
This button doesn't seem to be working for me or it's so delayed that it seems like it's not working. I suspect there may be a threading issue or something where the abort is being blocked, perhaps? Trying to abort an infinite loop should be a simple way of testing it.
