### ISSUE TITLE
Auto-generation of directory when using #load statement

### ISSUE THREAD

**Issue by anegg0** [Microsoft/workbooks#522]
### Steps to Reproduce

1. create a workbook with a #load statement pointing to a .csx document sitting in the same directory as the workbook
2. a new directory is generated containing a file named "index.workbook" as well as the .csx doc

### Expected Behavior
no directory is generated and the original file name doesn't change 

### Actual Behavior

a new directory is generated, the original file named is changed to "index.workbook"

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.5.0 |
| Git Branch | 1.5-release |
| Git Hash | 11f83dc |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component | Value |
| :- | :- |
| Windows | Microsoft Windows NT 10.0.17134.0 (64-bit) |
| CPU Cores | 2 |
| Physical Memory | 4 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Xamarin Simulator | 1010300018 |

#### VisualStudio.15.Preview Components
| Component | Version |
| :- | :- |
| Visual Studio Community 2017 | 15.9.7-pre.1.0+28307.423 |
| Xamarin iOS | 12.2.1-15 |
| Xamarin Android | 9.1.7-0 |

#### VisualStudio.16.Preview Components
| Component | Version |
| :- | :- |
| Visual Studio Community 2019 | 16.0.0-pre.3.0+28608.199 |
| Xamarin iOS | 12.6.0-16 |
| Xamarin Android | 9.1.103-12 |

### Log File

[Xamarin Workbooks 2019-02-27.log](https://github.com/Microsoft/workbooks/files/2911727/Xamarin.Workbooks.2019-02-27.log)

**Comment by sandyarmstrong** [comment]
See https://github.com/Microsoft/workbooks/issues/518#issuecomment-455207245.

Basically, any time you use relative paths, you are converting your Workbook into a package. https://docs.microsoft.com/en-us/xamarin/tools/workbooks/workbook#workbooks-files-types may also be a useful read.

**Comment by anegg0** [comment]
This doesn't solve my issue, I would have appreciated having a choice over workbooks behavior, since the current one breaks my setup.

**Comment by sandyarmstrong** [comment]
I understand, and I agree that it is confusing. Unfortunately, at this time, if you want to use relative paths, you need to embrace the workbook package directory structure.

**Comment by anegg0** [comment]
noted, thanks.

**Comment by slodge** [comment]
I did start on a pull for non-directory behaviour - https://github.com/Microsoft/workbooks/pull/502 - but I've not progressed it. Still happy to put some work in, but not sure if it's aligned with the workbooks roadmap/vision

**Comment by anegg0** [comment]
thank you for letting me know, @slodge
