### ISSUE TITLE
Member signature help should not offer instance members on static or static members on instance

### ISSUE THREAD

**Issue by abock** [Microsoft/workbooks#64]
```csharp
new Regex ().$
```

Where the completion dropdown is at `$`, I am offered both static `Regex` members and instance members. I should only be offered instance members in this case.

**Comment by sandyarmstrong** [comment]
I can't repro this on Windows or Mac. What static members are you seeing?

**Comment by abock** [comment]
<img width="1168" alt="screen shot 2017-12-08 at 2 25 17 pm" src="https://user-images.githubusercontent.com/49539/33781718-ab0f6948-dc23-11e7-973d-20029c711434.png">

Completion includes static members in a context where invoking a static member is illegal.

**Comment by abock** [comment]
Similarly, instance members should not be offered for static cases:

<img width="710" alt="screen shot 2017-12-08 at 2 27 52 pm" src="https://user-images.githubusercontent.com/49539/33781821-0f7e996c-dc24-11e7-8a1b-3c46a98fc99f.png">

**Comment by sandyarmstrong** [comment]
Perfect, thank you. I misunderstood the bug to be about items showing up in the completion dropdown, not the signature help dropdown. Will fix.

**Comment by sandyarmstrong** [comment]
Will likely need to replicate some of the logic here: https://github.com/dotnet/roslyn/blob/3b6536f4a616e5f3b8ede940c63663a828e68b5d/src/Features/CSharp/Portable/SignatureHelp/InvocationExpressionSignatureHelpProvider_MethodGroup.cs#L44-L50
