### ISSUE TITLE
Windows: 3D sometimes disappears; resetting causes client to crash

### ISSUE THREAD

**Issue by sandyarmstrong** [Microsoft/workbooks#86]
### Environment

**[Log File](https://developer.xamarin.com/guides/cross-platform/workbooks/install/#Log_Files)**: https://gist.github.com/sandyarmstrong/2a2453f49ee403ae7182a87c8c1e46c1

#### Xamarin Workbooks
| Detail          | Value                       |
| :-------------- | :-------------------------- |
| Version         | 1.4.0-dev+76                |
| Git Branch      | master                      |
| Git Hash        | 81de4cc                     |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component       | Value                                      |
| :-------------- | :----------------------------------------- |
| Windows         | Microsoft Windows NT 10.0.16299.0 (64-bit) |
| CPU Cores       | 8                                          |
| Physical Memory | 32 GB                                      |

#### System-Installed Software
| Component         | Version    |
| :---------------- | :--------- |
| Xamarin Simulator | 1010200022 |

#### VisualStudio.15.IntPreview Components
| Component                     | Version                       |
| :---------------------------- | :---------------------------- |
| Visual Studio Enterprise 2017 | 15.5.0-pre.4.0+27107.1.d15rel |
| Xamarin iOS                   | 11.4.0-214                    |
| Xamarin Android               | 8.1.0-22                      |

#### VisualStudio.15.Preview Components
| Component                     | Version                |
| :---------------------------- | :--------------------- |
| Visual Studio Enterprise 2017 | 15.5.0-pre.3.0+27102.0 |
| Xamarin iOS                   | 11.4.0-98              |
| Xamarin Android               | 8.1.0-22               |

#### VisualStudio.15.Release Components
| Component                     | Version           |
| :---------------------------- | :---------------- |
| Visual Studio Enterprise 2017 | 15.4.1+27004.2005 |
| Xamarin iOS                   | 11.2.0-8          |
| Xamarin Android               | 8.0.0-33          |

### Steps to Reproduce

1. Create console workbook
2. Switch it to Android
3. When fully connected, switch to 3D view, click it (3D view should disappear)
4. Click reset button

### Expected Behavior

Maybe 3D view will reappear?

### Actual Behavior

Workbooks client crashes. See log.

I cannot consistently get the 3D view to disappear. It happens maybe 50% of the time, and is maybe related to how quickly you switch to View Inspector tab and click the 3D view. But once it does disappeaer, the crash is consistent.

Also, I've seen the 3D view disappear without switching agents for a workbook. I've seen it occur with the Inspector client, for example.

**Comment by lewing** [comment]
The relevant code is now very different and I haven't seen anything like the previous problem.  I think we should close this and reopen if if comes up again.

**Comment by sandyarmstrong** [comment]
Sorry to reopen, but I just experienced this with latest master.
